name: Script Test

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prep Test
        run: sudo chmod +x ectfd.sh
      - name: Test Script
        run: pwd && ./ectfd.sh