name: Script Test

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prep Test
        run: mv ectfd.sh .. && cd .. && ls -R
      - name: Test Script
        run: ./ectfd.sh